# Generated by Django 3.1.2 on 2021-12-15 02:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Draw', '0002_doodle_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drawing',
        ),
        migrations.AddField(
            model_name='doodle',
            name='actual_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actually_as', to='Draw.label'),
        ),
        migrations.AddField(
            model_name='doodle',
            name='country_code',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='doodle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doodle',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doodle',
            name='prediction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_as', to='Draw.label'),
        ),
        migrations.AddField(
            model_name='doodle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
