# Generated by Django 3.1.2 on 2021-12-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Draw', '0003_auto_20211215_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='word_en',
            field=models.CharField(max_length=512, null=True, unique=True),
        ),
    ]
