version: "3.3"

services:
  web:
    image: thongnd0200/django-app:latest
    container_name: django_app
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
          python manage.py makemigrations
          python manage.py migrate
          python manage.py runserver 0.0.0.0:8000
    volumes:
      - /code
    ports:
      - 8000:8000
    
  db:
    image: thongnd0200/pgsql
    container_name: pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  postgres_data: