version: "3.3"

services:
  django_gunicorn:
    volumes:
      - static:/static
    entrypoint: /code/entrypoint.sh
    env_file:
      - .env
    build:
      context: .
    expose:
      - "8000"
    depends_on:
      - db
    restart: unless-stopped
  
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "5100:5100"
    depends_on:
      - django_gunicorn
    restart: unless-stopped
    
  db:
    image: postgres:13
    container_name: pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Th1sIsV3r4Str0ngPassw0rd
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    restart: unless-stopped
    
  tfserve:
    image: tensorflow/serving 
    volumes:
      - ./PredictModel/doodle_predict:/models/doodle_predict
    environment:
      - MODEL_NAME=doodle_predict
    expose:
      - "8501"
    restart: unless-stopped

volumes:
  postgres_data:
  static:
