version: "3.3"

services:
  web:
    build: .
    container_name: django_app
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
          python manage.py makemigrations
          python manage.py migrate
          python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 5100:8000
    
  db:
    image: postgres:13
    container_name: pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Th1sIsV3r4Str0ngPassw0rd
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"

volumes:
  postgres_data:
