# Generated by Django 3.1.2 on 2021-10-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_key_id', models.BigIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('word', models.CharField(max_length=256, null=True)),
                ('recognized', models.BooleanField(default=False)),
                ('countrycode', models.CharField(max_length=16, null=True)),
            ],
        ),
    ]
